### ISSUE TITLE
Notifications: Scrolling, if more notifications available

### ISSUE THREAD

**Issue by cablemodmatt** [buildsgg/buildsgg#11]
Currently the notifications only shows up to 6 notifications. I think we should expand this and add a scroll wheel option. Maybe go up to 40-50 for future proofing purposes. I know my Facebook I have to scroll for a while overnight to catch up on notifications some days.

**Comment by bashgeek** [comment]
That should already be working. Can you please use the full bug template? What browser? Screenshot?

**Comment by cablemodmatt** [comment]
Just tried the latest version of Firefox and Chrome, neither have it 
working. Where do I do full bug template?

Screenshot attached - this is how it currently looks on Chrome and 
Firefox.

**Comment by bashgeek** [comment]
Should work properly now and showing the most recent 50 notifications (please keep in mind that some notifications group together - if it's happening in the same object - and count only as 1 notification)

**Comment by cablemodmatt** [comment]
I have the option for a scroller here now, however it doesn't allow me 
to scroll up or down.
