### ISSUE TITLE
Follow Function broken on Firefox

### ISSUE THREAD

**Issue by cablemodmatt** [buildsgg/buildsgg#13]
Looks like the follow button may be broken - I was trying to follow Ronnie and it isn't activating or doing anything.

**Comment by bashgeek** [comment]
Works fine for me. Please use the "bug" issue template (select "Bug" after clicking on "New issue"), I need exact steps on how to reconstruct this bug.

**Comment by cablemodmatt** [comment]
Where do I navigate to find the bug issue template? Not seeing that.

**Comment by cablemodmatt** [comment]
Ah sorry, I see what you're saying now.

https://builds.gg/ - Home page

Click on Ronnie's build:
https://builds.gg/builds/razer-build-10

Tried to click "Follow" but it acts as though the "Follow" button hasn't 
been clicked at all.

Firefox 63.0.1 (64-bit)

**Comment by bashgeek** [comment]
![image](https://user-images.githubusercontent.com/4669888/48394363-4079f580-e74e-11e8-9050-896787a78667.png)

and then

![image](https://user-images.githubusercontent.com/4669888/48394391-643d3b80-e74e-11e8-8b59-cbb9b7d8fbe0.png)

**Comment by bashgeek** [comment]
Fixed!

**Comment by cablemodmatt** [comment]
Don't hate me buddy, but it still isn't working. :D

**Comment by bashgeek** [comment]
Actually, it works. The user you mentioned never activated his account, hence the bug here is not the follow function it is that he was actually able to login and publish stuff with his account. This is fixed now and getting deployed soon.

**Comment by cablemodmatt** [comment]
Ahhhh okay, that makes sense, thanks buddy!
