### ISSUE TITLE
Comments: Add reply functionality

### ISSUE THREAD

**Issue by kul111** [buildsgg/buildsgg#15]
our comment section really feels like 1990 - I think we should implement the following features:

1) you should be able to LIKE a comment.
2) you should be able to reply to a comment and the reply is directly under the comment (just like FB does it).

**Comment by bashgeek** [comment]
Yeah the like thing is really a copyright infringement of Facebook, so not going that ;-)

Replies can be done and are somewhere on my lists, but will take some time and most likely won't be in the first public release.

**Comment by kul111** [comment]
Instead of “LIKE” can there be a small thumbs up symbol below the comment?

**Comment by bashgeek** [comment]
Yeah, but if I recall correctly they have a copyright on the actual behaviour of liking or reacting to comments, was very weird. However, I don't see any enhancement at all by adding this to our comments. What's the purpose?

**Comment by kul111** [comment]
people are just very used to this and like to "approve" comments - people are getting a big e-penis if many people approve their comment.

**Comment by bashgeek** [comment]
Well, ok, but it doesn't add any real functionality, but costs quite some time. Can be done, but not anytime soon, other stuff is more important.

**Comment by kul111** [comment]
got it - lets focus then on being able to comment below comments (replying to comments) once you got time.

**Comment by bashgeek** [comment]
Added reply functionality
