### ISSUE TITLE
"Most Popular Builds" Section

### ISSUE THREAD

**Issue by kul111** [buildsgg/buildsgg#21]
I think this section is very confusing because of the 3 options (recent, popular, best) we got as the headline never changes - I think it should be the following:

If "recent" is picked then the headline of this section should be "Most Recent Builds"

If "popular" is picked then the headline of this section should be "Most Popular Builds"

If "best" is picked then the headline of this section should be "Best Builds"

Things would be a little bit less confusing and more clear if you ask me.

**Comment by bashgeek** [comment]
Sounds reasonable. @lesterckl do you agree with the phrasing of the titles?

And: Which one should be the default (currently being "recent")?

**Comment by kul111** [comment]
recent should be default  IMO so the front page keeps changing.

**Comment by bashgeek** [comment]
Done, if any complains about the titles, please let me know :)

**Comment by lesterckl** [comment]
Phrasing looks good!
