### ISSUE TITLE
Product Part Search Enhancements

### ISSUE THREAD

**Issue by kul111** [buildsgg/buildsgg#3]
After people picked "CableMod" and "CableMod" for the brand when you type in any color then nothing comes up.

We should tweak this search engine for the "part" there so  when you type in a color then the suitable options for it come up.

Also is there any way that after you picked "CableMod" that you dont have to pick it again for the brand? We will be the only brand in that category and its a little redundant.

**Comment by bashgeek** [comment]
That's part of the (still to be done) search optimisations. It doesn't just affect CableMod, but all products for that matter.

**Comment by bashgeek** [comment]
Improved a lot!

At first for CableMod: If a category only has one brand in it, it'll select this automatically. That won't just work for CableMod, but every category that only has one brand associated.

Afterwards it loads all products and groups them for the user to toggle, or search which also has been significantly improved.
