### ISSUE TITLE
Build Views Count not working

### ISSUE THREAD

**Issue by kul111** [buildsgg/buildsgg#7]
the build view count doesnt seem to work - it only works for Daniels build but none of the others.

**Comment by bashgeek** [comment]
Maybe that's because my build is the only one getting views? 💃 
Yeah, broken, will have a look.

**Comment by bashgeek** [comment]
Yeah, still doesn't work on production.. reopening

**Comment by bashgeek** [comment]
Now it's working properly. Reset all stats along the way.
